#!/bin/bash

# a2v - "audio to video". generate a video from a sound file and an image.
# useful for when you want to upload music to youtube or other video sharing sites.
# the image file can't be a gif.
# if the image file is big then generating the video will take a lot longer.

# i found this online and modified it slightly. i don't remember/can't find the original source.

# usage:
# a2v <image-file> <audio-file> [output-filename]

# examples:
#
# use cover.jpg as the image and happybirthday.mp3 as the audio file. the output file will be 'happybirthday.avi' in the current directory:
# a2v cover.jpg happybirthday.mp3
#
# use cover.jpg as the image, happybirthday.mp3 as the audio file, and dmca.avi as the output filename:
# a2v cover.jpg happybirthday.mp3 dmca.avi

# code:

FFMPEG=`which ffmpeg`
if [ "$FFMPEG" = "" ] ; then
    echo "ffmpeg is required to generate the video."
    exit 1
fi

if (( $# < 2 )) ; then
    echo "Usage: a2v <image-file> <audio-file> [output-filename]"
    exit 0
fi

if [ ! -f "$1" ] ; then
    echo "Source image '$1' not found."
    exit 1
else
    # FIX: check if the image is a gif, and if so, create a temporary copy that is converted to png.
    IMAGE="$1"
fi

if [ ! -f "$2" ] ; then
    echo "Source audio '$2' not found."
    exit 1
else
    AUDIO="$2"
    LENGTH="`ffprobe -i "$AUDIO" -show_entries format=duration -loglevel quiet -of csv="p=0"`"
fi

if (( $# == 2 )) ; then
    OUTPUT="`basename "$AUDIO" .mp3`.avi"
    echo "Assuming output filename '$OUTPUT'."
else
    OUTPUT="$3"
fi

if [ -f "$OUTPUT" ] ; then
    echo "Output file '$OUTPUT' exists.  Overwrite? (y/n)"
    read CONFIRM
    if [ "$CONFIRM" == "y" ] ; then
        echo "Overwriting '$OUTPUT'"
    else
        if [ "$CONFIRM" == "Y" ] ; then
            echo "Overwriting '$OUTPUT'"
        else
            echo "Operation canceled."
            exit 1
        fi
    fi
fi

$FFMPEG -i "$AUDIO" -loop 1 -i "$IMAGE" -r 1 -shortest -t $LENGTH "$OUTPUT"
