#!/usr/bin/env fish
# autocrop - Automatically trim blank edges of an image.
# Copies the original image to /tmp first in case you want to restore it later.

set -- script "$(basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Automatically trim blank edges of an image."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

for file in $argv
    mkdir -p /tmp/autocrop/
    cp $file /tmp/autocrop/
    convert $file -fuzz '50%' -trim $file
end
