#!/usr/bin/env fish
# e- - Alias for "e -"; open an editor for the text passed via stdin.

set -- script "$(path basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Alias for \"e -\"; open an editor for the text passed via stdin."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

e -
