#!/usr/bin/env fish
# e-fg - Run Emacs in the foreground via the e script.

set -- script "$(path basename (status filename))"

argparse -n $script 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Run Emacs in the foreground via the \"e\" script."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

e --foreground $argv
