#!/usr/bin/env fish
# findvis - Find visual files.

set -- script "$(path basename (status filename))"

argparse -n "$script" --ignore-unknown 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Find visual files."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

findtype visual $argv
