#!/usr/bin/env fish
# findd - Find directory files.

set -- script "$(path basename (status filename))"

argparse -n "$script" --ignore-unknown 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Find directory files."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

findtype directory $argv
