#!/usr/bin/env fish
# lsd - List directory files.

set -- script "$(path basename (status filename))"

argparse -n "$script" --ignore-unknown 'h/help' -- $argv

if set -q _flag_h
    echo "$script - List directory files."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

ls -1 $argv | filter directory
