#!/usr/bin/env fish
# myip - Get your current public IP address.

# notes:
# https://serverfault.com/questions/1007184/how-to-check-ipv6-address-via-command-line

set -- script "$(path basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Get your current public IP address."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

curl ifconfig.me
