#!/usr/bin/env fish
# myip - Get your current public IP address.

set -- script "$(basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Get your current public IP address."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

curl ifconfig.me
