#!/usr/bin/env fish
# rfile - output a random file in the current directory.
# with an argument ARG, output a random file in any of a maximum of ARG subdirectories.

if test (count $argv) = 0
    set depth 1
else
    set depth $argv[1]
end

find -maxdepth $depth | shuf | head -1

