#!/usr/bin/env fish
# run-if-not: run a program if it's not already running.

# example:
#
# run-if-not emacs

set res (basename (echo $argv[1]))

if not pgrep "^$res\$" >/dev/null
    exec $argv
end
