#!/usr/bin/env fish
# snds - Get a list of all programs using sound devices.

set -- script "$(path basename (status filename))"

argparse -n $script 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Get a list of all programs using sound devices."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

lsof 2>/dev/null | grep snd | string replace --regex '^(\S+)\s+.+\s+(\S+)$' '$1 $2' | sort | uniq | column -t -o '    '
