#!/usr/bin/env fish
# ssuspend - "Screen suspend". Simply turns off your monitor(s).
# 'ssuspend on' to unsuspend.

argparse -n ssuspend 'h/help' -- $argv

if test -n "$_flag_h"
    echo "ssuspend - \"Screen suspend\". Simply turns off your monitor(s)."
    echo "Usage: ssuspend [arguments] [on/off]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

if contains -- "$argv[1]" "on" "1"
    set action on
else
    # per https://wiki.archlinux.org/title/Display_Power_Management_Signaling :
    # "Note that DPMS was developed for CRT monitors, and on LCD displays, there is normally no difference between the standby, suspend and off modes."
    # "off" is used as per the suggestion in xscreensaver-command's man page.
    set action off
end

xset dpms force $action
