#!/usr/bin/env fish
# ssuspend - "screen suspend"
# suspends your monitor, of course!
# 'ssuspend on' to unsuspend.

argparse -n ssuspend 'h/help' -- $argv

if test -n "$_flag_h"
    echo "ssuspend - suspend screens."
    echo "Usage: ssuspend [arguments] [on/off]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

if contains -- "$argv[1]" "" "on" "1"
    set action on
else
    set action suspend
end

xset dpms force $action
