#!/usr/bin/env fish
# tag-count - Print all TMSU tags next to a count of their uses.
# Tip: you can pipe to sort -n to sort by the count.

set -- script "$(path basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Print all TMSU tags next to a count of their uses."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

for i in (tmsu tags -1)
    set count (tmsu files $i | nl | tail -1 | awk '{print $1}')
    if test -z $count
        set count 0
    end
    echo "$count $i"
end

