#!/usr/bin/env fish
# translate-selected - translate the selected text, showing the result with a popup dialog
# Requirements: translate-shell, xclip, zenity
# See also: define-selected

argparse -n translate-selected 'h/help' -- $argv

if test -n "$_flag_h"
    echo "translate-selected - translate the selected text, showing the result with a popup dialog."
    echo "Usage: translate-selected [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

set translation (xclip -o -selection primary | trans -brief | string collect)

zenity --info --width=800 --text="$translation"
