#!/usr/bin/env fish
# run-if-not: run a program if it's not already running.

# example:
#
# run-if-not emacs

# code:

argparse -n run-if-not --ignore-unknown 'h/help' -- $argv

if test -n "$_flag_h"
    echo "run-if-not - run a program if it's not already running."
    echo "Usage: run-if-not [arguments] [program and arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

if not pgrep "^$argv[1]\$" >/dev/null 2>/dev/null
    exec $argv
end
