#!/usr/bin/env fish
# v- - Alias for "v -"; open an image viewer for the files passed via stdin.

set -- script "$(path basename (status filename))"

argparse -n "$script" 'h/help' -- $argv

if set -q _flag_h
    echo "$script - Alias for \"v -\"; open an image viewer for the files passed via stdin."
    echo "Usage: $script [arguments]"
    echo
    echo "  -h/--help - Print help and exit."
    exit
end

v -
